---
provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
- name: centos-6-5-x64
  driver:
    name: digitalocean

- name: centos-7-0-x64
  driver:
    name: digitalocean

- name: debian-7-0-x64
  driver:
    name: digitalocean
  run_list:
  - recipe[apt]

- name: ubuntu-12-04-x64
  driver:
    name: digitalocean
  run_list:
  - recipe[apt]

- name: ubuntu-14-04-x64
  driver:
    name: digitalocean
  run_list:
  - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[rabbitmq::default]
  - name: default-use-distro-version
    run_list:
      - recipe[rabbitmq::default]
    attributes:
      rabbitmq:
        use_distro_version: true
    excludes: ["centos-6-5-x64", "centos-7-0-x64"]
  - name: cluster
    run_list:
      - recipe[rabbitmq::default]
    attributes:
      rabbitmq:
        cluster: true
        cluster_disk_nodes: ['rabbit@localhost']
  - name: lwrps
    run_list:
      - recipe[rabbitmq_test::lwrps]
